AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Stack used for test Lupe services

service: lupe-service

custom:
  config: ${file(./config/${opt:stage}.js):config}
  empty: ""
  browserify:
    exclude:
      - aws-sdk

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    NODE_ENV: ${opt:stage}
    SERVERLESS_STAGE: ${opt:stage}
    STAGE: ${opt:stage}
    CHAR_BUCKET: ${self:custom.config.charBucket}
    SOURCE_ENVIRONMENT: ${self:custom.config.sourceEnvironment}
  iamRoleStatements: ${file(./services-config/iam/roleStatements.yaml)}
  logRetentionInDays: 3

package:
  individually: true
  include:
    - config

functions: ${file(./services-config/${opt:service}.yaml):functions}

plugins:
  - serverless-plugin-browserifier
  - serverless-plugin-warmup
